server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Serve files directly when they exist, otherwise fallback to index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Optional: tune gzip
  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
